workflows:
  android-debug:
    name: Build Android APK (Debug)
    max_build_duration: 30
    instance_type: mac_mini_m1
    
    environment:
      flutter: 3.41.2
    
    scripts:
      - name: دریافت وابستگی‌ها
        script: |
          flutter pub get
      
      - name: ساخت APK (Debug)
        script: |
          flutter build apk --debug --verbose
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@gmail.com